server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
        - id: commonService
          uri: lb://commonService
          predicates:
            - Path=/common/**
        #            - Cookie=user,/**
        - id: timeValueService
          uri: lb://timeValueService
          predicates:
            - Path=/timeValue/**
      default-filters:
        - AddRequestHeader=origin,gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            #            allowedOrigins: "http://192.168.1.102:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
            max-age: 360000
  redis:
    host: 192.168.157.100
    port: 6379
    database: 0
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

