server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**
        - id: commonService
          uri: lb://commonService
          predicates:
            - Path=/common/**
        #            - Cookie=user,/**
        - id: timeValueService
          uri: lb://timeValueService
          predicates:
            - Path=/timeValue/**
      default-filters:
        - AddRequestHeader=origin,gateway
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"