server:
  port: 8010
spring:
  application:
    name: userService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_school?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
feign:
  client:
    config:
      default:
        logger-level: basic