server:
  port: 8010
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_school
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
