server:
  port: 8011
spring:
  application:
    name: timeValueService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_school?useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: localhost:8848
